apiVersion: apps/v1
kind: Deployment
metadata:
  name: onebeservicems-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onebeservicems
  template:
    metadata:
      labels:
        app: onebeservicems
    spec:
      containers:
        - name: onebeservicems
          image: pavloskkr/onebeservicems:latest
          ports:
            - containerPort: 9002

---

apiVersion: v1
kind: Service
metadata:
  name: onebeservicems-service
spec:
  selector:
    app: onebeservicems
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: LoadBalancer
